#pragma once

#include <cstdint>

enum Opcodes : uint8_t {
  OPERAND_SIZE_OVERRIDE = 0x66,
  ADDRESS_SIZE_OVERRIDE = 0x67,
  LOCK = 0xF0,
  ES_SEGMENT_OVERRIDE = 0x26,
  CS_SEGMENT_OVERRIDE = 0x2E,
  SS_SEGMENT_OVERRIDE = 0x35,
  DS_SEGMENT_OVERRIDE = 0x3E,
  FS_SEGMENT_OVERRIDE = 0x64,
  GS_SEGMENT_OVERRIDE = 0x65,
};
